name: Generate Terraform Documentation

on:
  push:
    branches:
      - main
      - master
  #   paths:
  #     - '**.tf'
  #     - '**.tfvars'
  # pull_request:
  #   paths:
  #     - '**.tf'
  #     - '**.tfvars'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - lab01
          - lab02
          - lab03
          - lab04
          - lab05
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Terraform docs for ${{ matrix.directory }}
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          working-dir: ${{ matrix.directory }}
          output-file: README.md
          output-method: inject
          git-push: "true"
          config-file: .terraform-docs.yml
